spring:
  application.name: devices-configuration
  main:
    banner-mode: off
  datasource:
    driverClassName: org.postgresql.Driver
    hikari:
      maximumPoolSize: 15
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  liquibase:
    change-log: classpath:db/db.changelog.yaml
  kafka.consumer:
    group-id: devices-configuration-default
    auto-offset-reset: earliest
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://keycloak.auth/realms/iot"
server:
  shutdown: graceful
  error:
    include-message: never

management:
  metrics.export.prometheus.enabled: true
  endpoint.env.enabled: true
  endpoints.web.exposure.include: "health,info,env,prometheus"

logging.level:
  org.apache.catalina.startup.DigesterFactory: ERROR
  org.apache.catalina.util.LifecycleBase: ERROR
  org.apache.coyote.http11.Http11NioProtocol: WARN
  org.apache.sshd.common.util.SecurityUtils: WARN
  org.apache.tomcat.util.net.NioSelectorPool: WARN
  org.eclipse.jetty.util.component.AbstractLifeCycle: ERROR
  org.hibernate.validator.internal.util.Version: WARN
  org.springframework.boot.actuate.endpoint.jmx: WARN
  org.springframework.web: INFO
  org.apache.kafka: WARN
  org.apache.kafka.clients.consumer.ConsumerConfig: INFO
  org.apache.kafka.clients.producer.ProducerConfig: INFO
  org.apache.kafka.clients.admin.AdminClientConfig: INFO
  org.apache.kafka.common.utils.AppInfoParser: INFO
  org.apache.kafka.streams.StreamsConfig: INFO
